#!/bin/bash
# vim: et sr sw=4 ts=4 smartindent syntax=sh:
# credstash - replacement for credstash binary, using docker opsgang/credstash:stable
#
# =================================================
# Put this in your file in your PATH, and chmod a+x
# =================================================
#
# See .examples/README.md for more details.
#
_check_var_defined() {
    local var_name="$1"
    local var_val="${!var_name}"
    if [[ -z $var_val ]]; then
        return 1
    fi
}

required_vars() {
    local rc=0
    local required_vars="$1"
    local this_var
    for this_var in $required_vars; do
        if ! _check_var_defined $this_var
        then
            echo "ERROR $0: \$$this_var must be set in env" >&2
            rc=1
        fi
    done

    return $rc
}

container_as_cmd() {
    local cmd_args="$@"
    required_vars "CONTAINER_NAME TAGGED_IMG" || return 1
    sudo docker kill $CONTAINER_NAME >/dev/null 2>&1
    sudo docker rm -f $CONTAINER_NAME >/dev/null 2>&1

    docker run --name $CONTAINER_NAME --rm $DOCKER_OPTS $TAGGED_IMG $cmd_args
}

# unique_id(): ... used to minimise race-conditions when you run cmd more than once
#              in the same second.
unique_id() {
    echo $(( $(shuf -i 000001-999999 -n1) * $(shuf -i 000001-999999 -n1) ))
}

export CONTAINER_NAME="${CONTAINER_NAME:-credstash_$(date +'%Y%m%d%H%M%S')_$(unique_id)}"
export TAGGED_IMG=opsgang/credstash:stable
container_as_cmd "$@"
